### ISSUE TITLE
socket.gaierror

### ISSUE THREAD

**Issue by wolfrust** [wolfrust/bannoti#12]
Happens on losing internet connection.

```
E:\Toolz\Main\Bannoti>bannoti.exe run


                     ____                          _   _
                     | __ )  __ _ _ __  _ __   ___ | |_(_)
                     |  _ \ / _` | '_ \| '_ \ / _ \| __| |
                     | |_) | (_| | | | | | | | (_) | |_| |
                     |____/ \__,_|_| |_|_| |_|\___/ \__|_|

                                        Desktop notification tool for banano (https://banano.cc)
                                         by Mateo Cruz  (https://github.com/wolfrust)



Using https://api-beta.banano.cc as API provider on port 443

Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 73, in create_connection
  File "socket.py", line 953, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002630C55EA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-beta.banano.cc', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002630C55EA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bannoti.py", line 106, in <module>
  File "bananopy\banano.py", line 27, in account_balance
  File "bananopy\banano.py", line 16, in call
  File "requests\api.py", line 117, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-beta.banano.cc', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002630C55EA60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
[17532] Failed to execute script 'bannoti' due to unhandled exception!

E:\Toolz\Main\Bannoti>



```

**Comment by wolfrust** [comment]
exception handling added - e11ec2a456c030589a8a165a6730100b75f9d3d1
